import streamlit as st
from datetime import datetime, timedelta
import pandas as pd

# Page Configuration
st.set_page_config(page_title="Hospital Optometry Rigidity Stress-Planner", layout="wide")

st.title("Hospital Optometry Template Optimization & Risk Dashboard")
st.markdown("""
This simulator models template stress under strict operational constraints: **Standard/Complex exams require 20 minutes of 
uninterrupted face-to-face contact time**, and **Overbooks require 10 minutes**. 
Charting is mathematically forced outside of these face-to-face windows, dynamically exposing risks to lunch breaks and staff overtime.
""")

# --- SIDEBAR: SCHEDULING PARAMETERS ---
st.sidebar.header("1. Clinic Session Timing")
start_time = st.sidebar.time_input("Clinic Start", value=datetime.strptime("08:00", "%H:%M"))
lunch_start_time = st.sidebar.time_input("Lunch Start", value=datetime.strptime("12:00", "%H:%M"))
lunch_min = st.sidebar.number_input("Lunch Duration (mins)", value=60, step=15)
end_time = st.sidebar.time_input("Clinic End", value=datetime.strptime("17:00", "%H:%M"))

st.sidebar.header("2. Template Grid & Buffers")
grid_inc = st.sidebar.selectbox("System Grid Increment (mins)", [10, 15, 20, 30], index=2)
am_buffers = st.sidebar.slider("Morning Catch-up Slots (AM Buffers)", 0, 5, 3)
pm_buffers = st.sidebar.slider("Afternoon Catch-up Slots (PM Buffers)", 0, 5, 2)

st.sidebar.header("3. 10-Min Overbook Simulation")
if am_buffers > 0:
    am_overbooks = st.sidebar.slider("AM 10-Min Overbooks", 0, int(am_buffers), 0)
else:
    am_overbooks = 0

if pm_buffers > 0:
    pm_overbooks = st.sidebar.slider("PM 10-Min Overbooks", 0, int(pm_buffers), 0)
else:
    pm_overbooks = 0

total_overbooks = am_overbooks + pm_overbooks
total_configured_buffers = am_buffers + pm_buffers

# --- HELPER FUNCTION: SESSION GENERATOR ---
def generate_session_slots(session_start, session_end, buffer_limit, grid):
    session_data = []
    curr = session_start
    total_session_min = (session_end - session_start).total_seconds() / 60
    
    potential_slots = int(total_session_min // grid)
    if potential_slots <= 0:
        return []

    buffers_placed = 0
    spacing = max(1, potential_slots // (buffer_limit + 1)) if buffer_limit > 0 else 99
    
    for i in range(1, potential_slots + 1):
        is_buffer = (buffers_placed < buffer_limit and i % spacing == 0)
        duration = grid * 2 if is_buffer else grid
        
        if curr + timedelta(minutes=duration) > session_end + timedelta(minutes=1):
            break
            
        label = "🟠 Complex / Catch-up" if is_buffer else "🟢 Standard Exam"
        session_data.append({
            "Start Time": curr.strftime("%I:%M %p"),
            "Type": label,
            "Duration": duration  
        })
        curr += timedelta(minutes=duration)
        if is_buffer: buffers_placed += 1
            
    return session_data

# --- DATA PROCESSING ---
clinic_start_dt = datetime.combine(datetime.today(), start_time)
lunch_start_dt = datetime.combine(datetime.today(), lunch_start_time)
lunch_end_dt = lunch_start_dt + timedelta(minutes=lunch_min)
clinic_end_dt = datetime.combine(datetime.today(), end_time)

am_schedule = generate_session_slots(clinic_start_dt, lunch_start_dt, am_buffers, grid_inc)
pm_schedule = generate_session_slots(lunch_end_dt, clinic_end_dt, pm_buffers, grid_inc)

# Calculate total time blocks generated by the template grid
total_am_mins = sum([x['Duration'] for x in am_schedule])
total_pm_mins = sum([x['Duration'] for x in pm_schedule])
total_clinic_day_mins = total_am_mins + total_pm_mins

# Calculate distinct scheduled item baselines
total_standard_slots = sum(1 for x in (am_schedule + pm_schedule) if x["Type"] == "🟢 Standard Exam")
total_catchup_slots = sum(1 for x in (am_schedule + pm_schedule) if x["Type"] == "🟠 Complex / Catch-up")

# Display processing for layout grid
def process_session_display(session_slots, overbooks_left):
    session_list = []
    for item in session_slots:
        if item["Type"] == "🟠 Complex / Catch-up" and overbooks_left > 0:
            remaining_buffer_space = max(0, item["Duration"] - 10)
            session_list.append({
                "Start Time": item["Start Time"], 
                "Type": "🚨 OVERBOOKED BLOCK (10m Focused Contact Injected)", 
                "Duration": f"10m Face-to-Face + {remaining_buffer_space}m unallocated buffer"
            })
            overbooks_left -= 1
        else:
            session_list.append({
                "Start Time": item["Start Time"], 
                "Type": item["Type"], 
                "Duration": f"{item['Duration']} min"
            })
    return session_list

am_display = process_session_display(am_schedule, am_overbooks)
pm_display = process_session_display(pm_schedule, pm_overbooks)
display_list = am_display + [{"Start Time": lunch_start_time.strftime("%I:%M %p"), "Type": "🍴 LUNCH BREAK", "Duration": f"{lunch_min} min"}] + pm_display

# --- OUTPUT: SCHEDULE TEMPLATE ---
st.subheader("Simulated Grid Template (Strict Contact Footprint Model)")
df_display = pd.DataFrame(display_list)
st.table(df_display)

# --- METRICS & BENCHMARKING ---
st.divider()
st.subheader("Operational & Productivity Analytics")

total_daily_encounters = total_standard_slots + total_catchup_slots + total_overbooks
effective_functional_buffers = max(0, total_configured_buffers - total_overbooks)

m1, m2, m3 = st.columns(3)
with m1:
    st.metric("Total Daily Volume", f"{total_daily_encounters} Patients", delta=f"+{total_overbooks} Overbooks" if total_overbooks > 0 else None)
    st.caption(f"Standard Base: {total_standard_slots} | Intact Catch-up: {effective_functional_buffers} | Overbooks: {total_overbooks}")
with m2:
    # Rigid constraint math
    total_face_to_face_mins = (total_standard_slots * 20.0) + (total_catchup_slots * 20.0) + (total_overbooks * 10.0)
    st.metric("Total Contact Time", f"{total_face_to_face_mins:.0f} mins")
    st.caption("Pure face-to-face physician contact requirement")
with m3:
    if total_daily_encounters >= 15.9:
        st.success("Elite Tier (90th Percentile)")
    elif total_daily_encounters >= 13.6:
        st.info("High Productivity (75th Percentile)")
    elif total_daily_encounters >= 11.4:
        st.warning("Median Tier (50th Percentile)")
    else:
        st.error("Below National Median")
    st.caption("SullivanCotter Benchmark Rank")

# --- FIXED SECTION: RIGID QUALITY, CHARTING, AND LUNCH MATH ---
st.divider()
st.subheader("Quality Operations & Session Liabilities")

# Calculating AM Session Specifics
am_standard = sum(1 for x in am_schedule if x["Type"] == "🟢 Standard Exam")
am_catchup = sum(1 for x in am_schedule if x["Type"] == "🟠 Complex / Catch-up")
am_contact_required = (am_standard * 20.0) + (am_catchup * 20.0) + (am_overbooks * 10.0)

# Morning charting room is whatever is left over from the raw AM grid runtime
am_leftover_mins = max(0, total_am_mins - am_contact_required)
am_patients = am_standard + am_catchup + am_overbooks

# Benchmark: A safe charting speed requires 6 minutes of paperwork/documentation per encounter
target_chart_time_needed_am = am_patients * 6.0
am_charting_deficit = max(0, target_chart_time_needed_am - am_leftover_mins)

# Operational Inference: If AM leftover minutes cannot clear morning charts, the doctor charts into lunch
lunch_compression = min(lunch_min, am_charting_deficit)
net_rest_lunch = max(0, lunch_min - lunch_compression)

# Calculating PM Session Specifics
pm_standard = sum(1 for x in pm_schedule if x["Type"] == "🟢 Standard Exam")
pm_catchup = sum(1 for x in pm_schedule if x["Type"] == "🟠 Complex / Catch-up")
pm_contact_required = (pm_standard * 20.0) + (pm_catchup * 20.0) + (pm_overbooks * 10.0)

pm_leftover_mins = max(0, total_pm_mins - pm_contact_required)
pm_patients = pm_standard + pm_catchup + pm_overbooks
target_chart_time_needed_pm = pm_patients * 6.0
pm_charting_deficit = max(0, target_chart_time_needed_pm - pm_leftover_mins)

# Operational Inference: Remaining PM charting deficit forces end-of-day staff/physician overtime
pm_overtime_drift = pm_charting_deficit

# Total Daily Documentation Buffer
total_leftover_chart_mins = am_leftover_mins + pm_leftover_mins
true_chart_time_per_pt = total_leftover_chart_mins / total_daily_encounters if total_daily_encounters > 0 else 0

q_col1, q_col2, q_col3 = st.columns(3)

with q_col1:
    if true_chart_time_per_pt >= 6.0:
        st.metric("Net Charting Space / Pt", f"{true_chart_time_per_pt:.1f} min", "Optimal Structure")
    elif true_chart_time_per_pt >= 3.0:
        st.metric("Net Charting Space / Pt", f"{true_chart_time_per_pt:.1f} min", "Rushed Documentation Pace", delta_color="off")
    else:
        st.metric("Net Charting Space / Pt", f"{true_chart_time_per_pt:.1f} min", "Severe Backlog Risk", delta_color="inverse")
    st.caption("Available documentation minutes left over outside of face-to-face constraints.")

with q_col2:
    if lunch_compression == 0:
        st.success(f"Full Lunch Protected ({net_rest_lunch:.0f} mins remaining)")
    elif net_rest_lunch >= 30:
        st.warning(f"⚡ Lunch Compressed (Charity Charting: {lunch_compression:.0f}m | Rest: {net_rest_lunch:.0f}m)")
    else:
        st.error(f"🚨 Lunch Lost (Rest: {net_rest_lunch:.0f}m | Forced Charting: {lunch_compression:.0f}m)")
    st.caption("Minutes of the lunch window absorbed by morning documentation requirements.")

with q_col3:
    if pm_overtime_drift <= 5:
        st.metric("End-of-Day Overtime Drift", "None (< 5m)", "Optimal Session Close")
    else:
        st.metric("End-of-Day Overtime Drift", f"+{int(pm_overtime_drift)} mins", "Staff & Provider Burnout", delta_color="inverse")
    st.caption("Estimated clinic delay forced by unallocated afternoon documentation backlogs.")
